apiVersion: v1
kind: Pod # TODO make these deployments later
metadata:
  name: testpod-kata
  annotations:
    io.kubernetes.cri-o.TrustedSandbox: "false"
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  containers:
  - name: testpod-kata
    image: "busybox"
    command:
    - sleep
    - "3600"
